log:
  # 是否开启日志源记录，如果开启会在日志中显示调用日志所在的文件和行号
  add-source: true
  # 指定日志级别，可选值：debug, info, warn, error
  level: info
  # 指定日志显示格式，可选值 text, json
  format: json
  # 指定日志输出位置, 可以是标准输出stdout, stderr或具体文件路径
  output-path: stdout
